# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: detected.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='detected.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x64\x65tected.proto\"C\n\nDetections\x12\x0b\n\x03\x63\x61r\x18\x01 \x01(\r\x12\x0e\n\x06person\x18\x02 \x01(\r\x12\x0b\n\x03\x63\x61t\x18\x03 \x01(\r\x12\x0b\n\x03\x64og\x18\x04 \x01(\r\"E\n\x08\x44\x65tected\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\n\n\x02\x61t\x18\x02 \x01(\x03\x12\x1f\n\ndetections\x18\x03 \x01(\x0b\x32\x0b.Detectionsb\x06proto3'
)




_DETECTIONS = _descriptor.Descriptor(
  name='Detections',
  full_name='Detections',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='car', full_name='Detections.car', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='person', full_name='Detections.person', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cat', full_name='Detections.cat', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dog', full_name='Detections.dog', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=85,
)


_DETECTED = _descriptor.Descriptor(
  name='Detected',
  full_name='Detected',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='Detected.host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='at', full_name='Detected.at', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='detections', full_name='Detected.detections', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=156,
)

_DETECTED.fields_by_name['detections'].message_type = _DETECTIONS
DESCRIPTOR.message_types_by_name['Detections'] = _DETECTIONS
DESCRIPTOR.message_types_by_name['Detected'] = _DETECTED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Detections = _reflection.GeneratedProtocolMessageType('Detections', (_message.Message,), {
  'DESCRIPTOR' : _DETECTIONS,
  '__module__' : 'detected_pb2'
  # @@protoc_insertion_point(class_scope:Detections)
  })
_sym_db.RegisterMessage(Detections)

Detected = _reflection.GeneratedProtocolMessageType('Detected', (_message.Message,), {
  'DESCRIPTOR' : _DETECTED,
  '__module__' : 'detected_pb2'
  # @@protoc_insertion_point(class_scope:Detected)
  })
_sym_db.RegisterMessage(Detected)


# @@protoc_insertion_point(module_scope)
